platform :ios, '10.0'
use_frameworks!

# ignore all warnings from all dependencies
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'PromiseKitDemo' do
  pod 'SnapKit'
  pod 'PromiseKit'
  pod "PromiseKit/CoreLocation"
  pod 'RxSwift'
  pod 'RxCocoa'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
